language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- 'pypy'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage erase
- ./test_wallpaperfm.py
after_success:
  coveralls

matrix:
  allow_failures:
    - python: '3.4'
    - python: 'pypy'
